### ISSUE TITLE
[1.14.3] Clientside code trys to load on the serverside.

### ISSUE THREAD

**Issue by ProsperCraft** [Shadows-of-Fire/Toast-Control#12]
I know this is a clientside mod, I was wonder if you could set up sidedness so it doesn't try to load on the server -

https://gist.github.com/ProsperCraft/2b3d686625e3d587df30da58bde29713

Thank you for updating, was so happy to get rid of the vanilla toasts!

**Comment by Shadows-of-Fire** [comment]
I can try to poke some things.  Forge removed the previously existing "only load on side x" markers.
