### ISSUE TITLE
A way to limit toast duration

### ISSUE THREAD

**Issue by dark-penguin** [Shadows-of-Fire/Toast-Control#15]
Am I missing something, or is there no way to limit the toast duration? I thought this was the main purpose of this mod.

I have some problem which results in dozens of "Some mod encountered an error..." toasts. I can limit them to very few toasts at a time, but it takes several minutes for all of them to show.

I thought "Force Display Time" is supposed to force a specific toast display time, but apparently it only forces a min time, and there is no way to force a max time?.. At least in the main menu - I'm not sure if "ticks" are "ticking" when the game is not running.

I do not want to block toasts telling me something is wrong, but I want to limit their time. (Now that I think about it, there is no way to disable "error" toasts either, unless I want to disable all "system" toasts or know a way to learn their class.)

(This is on Toast Control 1.12.2-1.8.1 , Forge 1.12.2-14.23.5.2847.)

**Comment by Shadows-of-Fire** [comment]
The main purpose of the mod is blocking toasts.

Also, any mod adding "an error has occurred" as a toast is a gross misuse of the system overall.

If you want to block a certain toast, enable the class logging, pull the class of that toast from the log, and block that class.  Blocking all system toasts has no real negative effect either, unless you're using the narrator.

**Comment by dark-penguin** [comment]
But wouldn't it be a good idea to be able to see the toasts, but not for too long?.. As a programmer, I don't want to ignore any output, but I want it to be less intrusive.
