### ISSUE TITLE
[Feature Request] Top-in animation

### ISSUE THREAD

**Issue by kil0byt3** [Shadows-of-Fire/Toast-Control#19]
Hello! Thanks for a wonderful mod that we're using in Rebirth of the Night. 

I was wondering if you accepted feature requests. It would be super cool to have an animation that came in from the top-down, much like the Transition from Left option in the config. This would allow for a more direct "in your face" notification of an achievement/toast. Currently, you can move the toast using your great options for X and Y control, but the Right and Left slide in anims look a bit weird when the toast is anywhere in the middle of the screen .

Is that something that would be considered?

**Comment by Shadows-of-Fire** [comment]
maybe™

I'd have to find the time to do it, and TC features are not entirely high on the priority list as of now.

**Comment by kil0byt3** [comment]
No worries. I appreciate you thinking about it!
