### ISSUE TITLE
【1.16.5】freeze at world create

### ISSUE THREAD

**Issue by AmyRose1288** [Shadows-of-Fire/Toast-Control#23]
with these settings:

	[client.blocked_toasts]
		#If recipe toasts are blocked.
		recipes = false
		#If all vanilla toasts are blocked.
		global_vanilla = false
		#If advancement toasts are blocked.
		advancements = false
		#If system toasts are blocked.
		system = false
		#If all non-vanilla toasts are blocked.
		global_modded = false
		#If all toasts are blocked.
		global = false
		#If tutorial toasts are blocked.
		tutorial = false
		#Toast Classes that are blocked from being shown.
		blocked_classes = []

100% freeze at world create

**Comment by Shadows-of-Fire** [comment]
This mod doesn't interact with world creation
