### ISSUE TITLE
If you set it to left, but also to come down from the top, they come down from the top right.

### ISSUE THREAD

**Issue by Jetpack-Cat** [Shadows-of-Fire/Toast-Control#26]
Setting it to left and come down from top should have them come down from the top left of the screen, not the right side of the screen.

most recent version for 1.16.5

**Comment by Jetpack-Cat** [comment]
This is still an issue in 1.16.5

**Comment by Shadows-of-Fire** [comment]
1.16.5 is not supported, this has been fixed for 1.18.
