### ISSUE TITLE
key.toast.control.category & key.toastcontrol.clear

### ISSUE THREAD

**Issue by WesTroy** [Shadows-of-Fire/Toast-Control#3]
I'm no modder, so forgive me if this is a dumb thought:

I think when you don't need "pack.meta", you should use "en_US.lang" (resource format 2) and not "en_us.lang" (resource format 3)... currently the Controls menu shows the unlocalized names for your new key/category. Or maybe it's something else entirely =)

Great mod - essential to packs - keep up the great work!

**Comment by Shadows-of-Fire** [comment]
Ah, yeah... I swear it was working in dev.
