### ISSUE TITLE
ShadowDistanceOption crash with new ToastControl jar

### ISSUE THREAD

**Issue by BrassMcCrafty** [Shadows-of-Fire/Toast-Control#33]
[latest.log](https://github.com/Shadows-of-Fire/Toast-Control/files/12195169/latest.log)

**Comment by SiverDX** [comment]
are you sure thats the correct log?
the error you mention though often stems from missing dependencies
meaning you either did not update placebo or forge itself

**Comment by WFPhantom** [comment]
I don't think you have the correct log, but i'm getting the same error, toast control is requesting placebo 8.1.1 which doesnt seem to exist as the latest ver of placebo is 8,1.0

**Comment by Shadows-of-Fire** [comment]
8.1.1 was still pending CF's "advanced virus scanning" phase, last I checked.  Not sure what's taking it so long

**Comment by Shadows-of-Fire** [comment]
Placebo 8.1.1 has now been approved
