### ISSUE TITLE
Toastcontrol disables nonvanilla gui buttons

### ISSUE THREAD

**Issue by mcenderdragon** [Shadows-of-Fire/Toast-Control#4]
https://github.com/mcenderdragon/Futurepack-API/issues/456

In Summary: I have added custom buttons to a custom gui of mine and it seems like yor mod sets the "visible" flag of one of them to false. Resseting the visible flag each frame to true fixes the problem. 

It took very long to find out this mod is causing the issue :/

Edit: After reading your code I can hardly belive this mod is causing the issue... maybe another one is involved...

**Comment by Shadows-of-Fire** [comment]
https://github.com/Shadows-of-Fire/FastWorkbench/blob/master/src/main/java/shadows/fastbench/proxy/BenchClientProxy.java#L45

**Comment by Shadows-of-Fire** [comment]
If these checks are not strict enough I guess I get to start checking the texY and texX provided to `GuiButtonImage`

**Comment by mcenderdragon** [comment]
My button is futurepack.common.gui.ButtonAspect and extends net.minecraft.client.gui.GuiButton, maybe you can implemented a class check. And also my disbaled button has id 10, so it is probably that.

**Comment by Shadows-of-Fire** [comment]
If your isnt an instanceof GuiButtonImage and doesn't match either of those relocs this check will fail, so a blacklist at that level wouldn't do anything

**Comment by mcenderdragon** [comment]
It is not, thats very weird, it seems like the `b instanceof GuiButtonImage` is ignored and only` b.id == 10` is used...

**Comment by Shadows-of-Fire** [comment]
Actually, its probably that stupid af no more recipe book mod.

**Comment by Shadows-of-Fire** [comment]
As I recall, that mod deletes all buttons in the game with id of 10.

**Comment by mcenderdragon** [comment]
well yeah thats would affect my guis...

**Comment by Shadows-of-Fire** [comment]
Gonna close this and move back to the futurepack issue

**Comment by mcenderdragon** [comment]
Sure
